version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
    #you also need to install packages or frameworks needed to build ur code in the install phase.
    #install angular CLI to build our code in the build phase. Commands executed as list items in the order u want to be executed.
    - npm install -g @angular/cli@17 #angular 17 cli version
    #new commands for unit testing
    # Chrome installation for Angular's unit tests
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /etc/apt/keyrings/chrome.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    - apt-get -y update
    - apt-get -y install google-chrome-stable

  pre_build:
    #install our project dependancies
    commands:
    - npm install
  build:
    #only changes build spec part. No artifacts here
    commands:
    - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
